version: '3.7'

volumes:
  orderer.example.com:
  peer0.hospital.example.com:
  peer0.patient.example.com:
  peer0.pharmacy.example.com:
  peer0.laboratory.example.com:
  peer0.insurance.example.com:

networks:
  fabric_healthcare:
    name: fabric_healthcare

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:17050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-material/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-material/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 17050:17050
    networks:
      - fabric_healthcare

  peer0.hospital.example.com:
    container_name: peer0.hospital.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.hospital.example.com
      - CORE_PEER_ADDRESS=peer0.hospital.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hospital.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital.example.com:7051
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17051
      # chaincode
      # - CORE_VM_DOCKER_ATTACHSTDOUT=true  # chaincode logging
    volumes:
        - ${DOCKER_SOCK}/:/host/var/run/docker.sock
        - ./crypto-material/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-material/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.hospital.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 17051:17051
    networks:
      - fabric_healthcare

  peer0.patient.example.com:
    container_name: peer0.patient.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.patient.example.com
      - CORE_PEER_ADDRESS=peer0.patient.example.com:7061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7061
      - CORE_PEER_CHAINCODEADDRESS=peer0.patient.example.com:7062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7062
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patient.example.com:7061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.patient.example.com:7061
      - CORE_PEER_LOCALMSPID=PatientMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17061
      # chaincode
      # - CORE_VM_DOCKER_ATTACHSTDOUT=true  # chaincode logging
    volumes:
        - ${DOCKER_SOCK}/:/host/var/run/docker.sock
        - ./crypto-material/peerOrganizations/patient.example.com/peers/peer0.patient.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-material/peerOrganizations/patient.example.com/peers/peer0.patient.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.patient.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7061:7061
      - 17061:17061
    networks:
      - fabric_healthcare


  peer0.pharmacy.example.com:
    container_name: peer0.pharmacy.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.pharmacy.example.com
      - CORE_PEER_ADDRESS=peer0.pharmacy.example.com:7071
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7071
      - CORE_PEER_CHAINCODEADDRESS=peer0.pharmacy.example.com:7072
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7072
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pharmacy.example.com:7071
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pharmacy.example.com:7071
      - CORE_PEER_LOCALMSPID=PharmacyMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17071
      # chaincode
      # - CORE_VM_DOCKER_ATTACHSTDOUT=true  # chaincode logging
    volumes:
        - ${DOCKER_SOCK}/:/host/var/run/docker.sock
        - ./crypto-material/peerOrganizations/pharmacy.example.com/peers/peer0.pharmacy.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-material/peerOrganizations/pharmacy.example.com/peers/peer0.pharmacy.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.pharmacy.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7071:7071
      - 17071:17071
    networks:
      - fabric_healthcare


  peer0.laboratory.example.com:
    container_name: peer0.laboratory.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.laboratory.example.com
      - CORE_PEER_ADDRESS=peer0.laboratory.example.com:7081
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7081
      - CORE_PEER_CHAINCODEADDRESS=peer0.laboratory.example.com:7082
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7082
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.laboratory.example.com:7081
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.laboratory.example.com:7081
      - CORE_PEER_LOCALMSPID=LaboratoryMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17081
      # chaincode
      # - CORE_VM_DOCKER_ATTACHSTDOUT=true  # chaincode logging
    volumes:
        - ${DOCKER_SOCK}/:/host/var/run/docker.sock
        - ./crypto-material/peerOrganizations/laboratory.example.com/peers/peer0.laboratory.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-material/peerOrganizations/laboratory.example.com/peers/peer0.laboratory.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.laboratory.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7081:7081
      - 17081:17081
    networks:
      - fabric_healthcare


  peer0.insurance.example.com:
    container_name: peer0.insurance.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.insurance.example.com
      - CORE_PEER_ADDRESS=peer0.insurance.example.com:7091
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7091
      - CORE_PEER_CHAINCODEADDRESS=peer0.insurance.example.com:7092
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7092
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurance.example.com:7091
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.example.com:7091
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17091
      # chaincode
      # - CORE_VM_DOCKER_ATTACHSTDOUT=true  # chaincode logging
    volumes:
        - ${DOCKER_SOCK}/:/host/var/run/docker.sock
        - ./crypto-material/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-material/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.insurance.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7091:7091
      - 17091:17091
    networks:
      - fabric_healthcare        


  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.hospital.example.com:7051
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.example.com/users/Admin@hospital.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-material:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.hospital.example.com
      - peer0.patient.example.com
      - peer0.pharmacy.example.com
      - peer0.laboratory.example.com
      - peer0.insurance.example.com
    networks:
      - fabric_healthcare
